### PR TITLE
Fix tokenizer and add new CL model 'bdi-cl-v0.2'

### PR DESCRIPTION
**Pull request by lyrain2001**

### CODE REVIEW

**Review by EduardoPena — APPROVED** [review]

**Review by aecio — CHANGES_REQUESTED** [review]
As discussed in the meeting:
- Need to remove all changes in the folder `experiments`  from this PR and commit changes to the new experiments repository. We are planning to remove this folder from this repository.
- Do not add sep_tokens in between words of the same cell

**Comment by EduardoPena** [comment]
We have been using black for code formatting. You can run `black ./bdikit/` before the commit. That will avoid breaking some tests.

**Comment by lyrain2001** [comment]
Thanks for the reminder!

**Comment by aecio** [comment]
@roquelopez Yes. I also force-pushed a commit to remove the formatting of files outside the `bdikit` folder and added a new commit with a link to the new model `bdi-cl-v0.2`. If it passes tests, this should be ready to merge.

**Review by aecio — APPROVED** [review]

**Pull request merged**
