### PR TITLE
refactor: Merge preview_value_mappings() and match_values() 

### PR DESCRIPTION
**Pull request by aecio**
The commit simplifies the API by removing preview_value_mappings() and merging its functionality into match_values(). The functionality provided by preview_value_mappings() is now fully supported by match_values().

### CODE REVIEW

**Comment by roquelopez** [comment]
I think we can be slightly more consistent with the outputs from `match_values`. When the input is a tuple it returns a dataframe (I like it), but when the input is a dataframe, it returns a list of dictionaries, with some extra attributes (e.g. `coverage`). It can be a little bit confusing, and users would need two scripts to parser the outputs. I think we should return a dataframe (when a tuple is the input) and a list of dataframes (when a dataframe is the input). Each output dataframe would continue to have the 3 columns (source, target, and similarity). To know which columns are, we can add the name of the columns as metadata.

```
result = {
    'source': ["a", "b", "c", "d"],
    'target': ["A", "B", "C", "D"],
    'similarity': [1.0, 1.0, 1.0, 1.0]
}

result = pd.DataFrame(result)
print("Original DataFrame:")
print(result)

result.attrs['source'] = {'name': 'id'}
result.attrs['target'] = {'name': 'ID'}
print("\nDataFrame with metadata:")
print(result)

# Access the metadata for each column
print("\nMetadata for source column:")
print(result.attrs['source'])

print("\nMetadata for target column:")
print(result.attrs['target'])
```

**Comment by aecio** [comment]
Using a data frame looks good but also creates inconsistencies with other functions. One of the reasons the output is a dictionary containing `source` and `target` keys is that this is the expected input format of `bdi.materialize_mapping()` and `update_mappings()`. So if we change it to a DataFrame, we need to modify these functions to support two different input cases. I'll investigate if this can be done easily.

**Comment by aecio** [comment]
@roquelopez this is ready to review again.

**Comment by roquelopez** [comment]
@aecio I made some minor changes. Feel free to merge!

**Review by roquelopez — APPROVED** [review]

**Comment by aecio** [comment]
Thanks, @roquelopez. I also added two more commits (function reordering and rename update_mappings) that we discussed.

**Pull request merged**
