### PR TITLE
Add tests and docs to value matching algorithms

### PR DESCRIPTION
**Pull request by aecio**
Resolves issue #48 .

### CODE REVIEW

**Comment by aecio** [comment]
@EduardoPena The AutoFuzzyJoin method you just added does not pass simple tests like the ones added to TFIDF and Edit Distance methods. Is that expected? Can you take a look if there is any implementation problem and add a test that works?

**Review by EduardoPena — APPROVED** [review]
All good.

**Comment by roquelopez** [comment]
I would like to close https://github.com/VIDA-NYU/bdi-kit/issues/48. So, will AutoFuzzyJoin have tests?

**Comment by aecio** [comment]
Let's close it for now. We're not sure if we want to keep AutoFuzzyJoin yet.

**Pull request merged**
